powerData <- read.table("..//Data Set//household_power_consumption.txt", header = TRUE, sep = ";")
twoDaysData <- powerData[powerData$Date %in% c("1/2/2007","2/2/2007"),]
twoDaysData$Global_active_power <- as.numeric(as.character(twoDaysData$Global_active_power))
x <- strptime(as.character(paste(twoDaysData$Date,twoDaysData$Time, sep=" ")), "%d/%m/%Y%n%T")
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
with(twoDaysData, plot(x, twoDaysData$Global_active_power, type="l", xlab = "", ylab = "Global Active Power (kilowatts)"))
with(twoDaysData, plot(x, twoDaysData$Voltage, type="l", xlab = "", ylab = "Voltage"))
with(twoDaysData, plot(x, twoDaysData$Sub_metering_1, type="l", xlab = "", ylab = "Global Active Power (kilowatts)"))
lines(x, twoDaysData$Sub_metering_2, col = "Red")
lines(x, twoDaysData$Sub_metering_3, col = "Blue")
legend("topright", 30, legend=c("Sub Metering 1", "Sub Metering 2", "Sub Metering 3"),col=c("Black", "Red", "Blue"), lty = 1, cex=0.8)
with(twoDaysData, plot(x, twoDaysData$Global_reactive_power, type="l", xlab = "", ylab = "Global Reactive Power"))
dev.off()