powerData <- read.table("..//Data Set//household_power_consumption.txt", header = TRUE, sep = ";")
twoDaysData <- powerData[powerData$Date %in% c("1/2/2007","2/2/2007"),]
twoDaysData$Global_active_power <- as.numeric(as.character(twoDaysData$Global_active_power))
png(filename = "plot3.png", width = 480, height = 480)
x <- strptime(as.character(paste(twoDaysData$Date,twoDaysData$Time, sep=" ")), "%d/%m/%Y%n%T")
with(twoDaysData, plot(x, twoDaysData$Sub_metering_1, type="l", xlab = "", ylab = "Global Active Power (kilowatts)"))
lines(x, twoDaysData$Sub_metering_2, col = "Red")
lines(x, twoDaysData$Sub_metering_3, col = "Blue")
legend("topright", 30, legend=c("Sub Metering 1", "Sub Metering 2", "Sub Metering 3"),col=c("Black", "Red", "Blue"), lty = 1, cex=0.8)
dev.off()